joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_3:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_4:
    has_velocity_limits: true
    max_velocity: 6.28
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_5:
    has_velocity_limits: true
    max_velocity: 6.28
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_6:
    has_velocity_limits: true
    max_velocity: 7.85
    has_acceleration_limits: true
    max_acceleration: 5.0
